version: '3.8'

services:
  shell:
    build:
      context: .
      args:
        APP_NAME: 'shell'
    container_name: docker-shell
  app1:
    build:
      context: .
      args:
        APP_NAME: 'app1'
    container_name: docker-app1
  gateway:
    image: nginx:1.22.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./gateway.nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - shell
      - app1
